name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Run 'make fmt'"
            exit 1
          fi

      - name: Run security scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          make security